### ISSUE TITLE
utility fails to run as root - claims to not be run as root

### ISSUE THREAD

**Issue by skraus86** [joshua-d-miller/macOSLAPS#49]
We're trying to troubleshoot using this with our AD laps, when we try to run as an admin OR as a root, it claims it is not being run as a root user.

![Screen Shot 2021-03-11 at 1 50 06 PM](https://user-images.githubusercontent.com/17663548/113332776-9fc10c00-92ef-11eb-9471-320761497b97.png)
![Screen Shot 2021-03-11 at 1 49 32 PM](https://user-images.githubusercontent.com/17663548/113332777-9fc10c00-92ef-11eb-82f1-454a6250b5b2.png)
![Screen Shot 2021-03-11 at 1 49 26 PM](https://user-images.githubusercontent.com/17663548/113332778-9fc10c00-92ef-11eb-94a1-33e9f05f594e.png)

**Comment by joshua-d-miller** [comment]
This is an executable so you do not need to use the open command. You can run it since I'm assuming you used the pkg installer by calling either `sudo macOSLAPS` or as root `macOSLAPS`. If you want to spell out the full path then you can do something like `/usr/local/laps/macOSLAPS` or `sudo /usr/local/laps/macOSLAPS`.

**Comment by skraus86** [comment]
That did it, thanks Joshua
