### ISSUE TITLE
Binary not signed correctly?

### ISSUE THREAD

**Issue by rx7raven** [joshua-d-miller/macOSLAPS#55]
Attempting to install macOSLAPS via provided package on Big Sur 11.4 but when invoked manually or automatic get the error that macOSLAPS with damage the machine.  Looked in console logs and found 'Binary is improperly signed'.  Did a codesign --verify --verbose on the binary and get 'CSSMERR_TP_CERT_REVOKED'.  Can't tell if this is an issue one my end or not.

**Comment by ilikebigruts** [comment]
and this when run with -resetPassword …

macOSLAPS -resetPassword
Info|2021-06-30 09:09:43|macOSLAPS|No Preferred Domain Controller Specified. Continuing...
Info|2021-06-30 09:09:43|macOSLAPS|Password Change is required as the LAPS password for <username>, has expired
2021-06-30 09:09:43.641 macOSLAPS[11574:17064871] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff32d42627 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6ba425bf objc_exception_throw + 48
	2   Foundation                          0x00007fff35405a4d -[NSConcreteTask launchWithDictionary:error:] + 5213
	3   macOSLAPS                           0x000000010ea679c8 $s9macOSLAPS5ShellC3run10launchPath9argumentsS2S_SaySSGtFZ + 648
	4   macOSLAPS                           0x000000010ea65770 $s9macOSLAPS15KeychainServiceC12loadPassword7serviceSSSg_AFtSS_tFZ + 5760
	5   macOSLAPS                           0x000000010ea70459 $s9macOSLAPS7ADToolsC15password_change15computer_recordySaySo8ODRecordCG_tFZ + 1177
	6   macOSLAPS                           0x000000010ea5bbaa $s9macOSLAPSAAyyF + 9082
	7   macOSLAPS                           0x000000010ea589c4 main + 20
	8   libdyld.dylib                       0x00007fff6cbeacc9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      macOSLAPS -resetPassword





On 30 Jun 2021, at 6:44 am, Kevin ***@***.***> wrote:


Attempting to install macOSLAPS via provided package on Big Sur 11.4 but when invoked manually or automatic get the error that macOSLAPS with damage the machine. Looked in console logs and found 'Binary is improperly signed'. Did a codesign --verify --verbose on the binary and get 'CSSMERR_TP_CERT_REVOKED'. Can't tell if this is an issue one my end or not.

**Comment by rx7raven** [comment]
Updated to macOSLAPS 2.1.0 Build 716 and it's working.
