### ISSUE TITLE
looking for instructions.

### ISSUE THREAD

**Issue by DBLClick** [joshua-d-miller/macOSLAPS#62]
Appears a lot of things changed with macOSLAPS with version 2.0 and also with BIG Sur.  

I noticed that you introduced two team ID in the source code and I would need to create a policy to grant permissions to run.  I'm wondering do you actually have installation instructions, for permissions and setup.

**Comment by munneco** [comment]
That would be really helpful for newbies (like me) so we can learn more and more about MacOS and that tool 😃

**Comment by joshua-d-miller** [comment]
@DBLClick,

You are correct that there are two team IDs as my goal was to transition from PSU's team to my own developer team since I was able to take the code with me when I left the university however PSU revoked the cert for the one Team ID so I don't think you will need to worry about that. You bring up a good point that I think a Wiki is probably needed to provide instructions on setup for things like Active Directory or MDM setups. I'm hoping over the holiday to add this information as things slow down a bit at my new gig.

Thanks!

**Comment by ShawnMGiesbrecht** [comment]
I've installed the latest package (2.1.0) on Big Sur (and so to be Monterey).
I tried to look for the file edu.psu.macoslaps.plist but not able to so I take it i have to create or use my MDM (which is Jamf)
Do you have any samples and or documentation (other than README.md)

**Comment by DBLClick** [comment]
Shawn,

I recommend that you use the JSON configuration file for jamf.  It works a lot easier to configure.

________________________________

**Comment by joshua-d-miller** [comment]
Hello all! A Wiki has been created which should go over how to setup macOSLAPS in your environment. If you have questions please let me know!
